### ISSUE TITLE
Remove release version from PLGX filename

### ISSUE THREAD

**Issue by Eagle3386** [ligos/readablepassphrasegenerator#1]
Implementing aforementioned removal within plugin's filename would allow for "download -> cut -> paste into KeePass's plugin folder" instead of the current "download -> rename -> cut -> paste" procedure.

**Comment by ligos** [comment]
You actually don't need to remove the version number for the plugin to be recognised in KeePass. I've updated the installation steps and screenshot to make that clear.

https://github.com/ligos/readablepassphrasegenerator/wiki/KeePass-Plugin-Step-By-Step-Guide

**Comment by Eagle3386** [comment]
While that's certainly true, you got me wrong: I'm not complaining about the existence of the version number within the file name due to having to manually remove it.

Instead, I'm complaining about it, because that's the only way to override the existing plugin file - the way you suggest to handle it creates several versions of the same file within the folder (and in turn requires even more steps to clean up that cluttering by deleting the older file).
Those extra steps are instantly obsolete as soon as the file's name stays the same throughout any new version.

**Comment by ligos** [comment]
Thanks for your clarification @Eagle3386. 
I'm happy with the current scheme where the version number as part of the filename. At this point, I'm not going to change it.

I understand there's one extra step when deploying it (download > cut > paste vs download > cut > delete old > paste). You could also Save As and overwrite the plugin directly. In the end, it's a very minor issue when the plugin is updated every 12-18 months.  (I'd expect you'd spend more time locating the new version on GitHub than renaming / deleting the old version).

Murray
