### ISSUE TITLE
Wiki refers to the Releases Tab

### ISSUE THREAD

**Issue by twocs** [ligos/readablepassphrasegenerator#10]
The [Readable Passphrase Generator Wiki ](https://github.com/ligos/readablepassphrasegenerator/wiki/KeePass-Plugin-Step-By-Step-Guide) says to use the Releases tab to get to the plugin.

However, I don't see this tab on github.com. 

I'd suggest adding to your Wiki: 
The direct url to access releases. It can take a while to figure out where it is located if the Releases tab is not missing.
https://github.com/ligos/readablepassphrasegenerator/releases

**Comment by twocs** [comment]
Location where Releases would be marked in red.
![image](https://user-images.githubusercontent.com/72763/104863100-012a3d80-5985-11eb-954b-8d45bbe1e438.png)

**Comment by twocs** [comment]
Looks like GitHub has moved Releases to the right column of the Code tab. An alternate improvement to the Wiki would be to point out this new location.

![image](https://user-images.githubusercontent.com/72763/104863250-3fbff800-5985-11eb-92ba-937acea9a1af.png)

**Comment by twocs** [comment]
This is the outdated image from the Wiki:
https://github.com/ligos/readablepassphrasegenerator/wiki/img/KeePass_Plugin_Step_By_Step_Guide_Github.png

![](https://raw.githubusercontent.com/wiki/ligos/readablepassphrasegenerator/img/KeePass_Plugin_Step_By_Step_Guide_Github.png)

Personally I cannot see the bar that reads 263 commits | 1 branch | 0 packages | 7 releases | 0 contributors | Apache-2.0
Looks like a GitHub GUI refresh.

![image](https://user-images.githubusercontent.com/72763/104863506-0d62ca80-5986-11eb-9b62-69dec1d298ad.png)

**Comment by ligos** [comment]
Sigh.
I remember looking for **Releases** on a different project the other day and struggling. Didn't even think it would impact my projects :-/

Thanks for the heads up.

**Comment by rminderhoud** [comment]
Just wanted to add that I also added this plugin to scoop-extras so it can
be installed using scoop. Thought you might like to know in case you wanted
to add that to the docs as well. See:
https://github.com/lukesampson/scoop-extras/blob/master/bucket/keepass-plugin-readable-passphrase.json

Install:
```
scoop install keepass
scoop install keepass-plugin-readable-passphrase
```

**Comment by ligos** [comment]
Fixed screenshot for Releases. And added link.
Added scoop install instructions

**Comment by rminderhoud** [comment]
Thanks @ligos and thanks for this great plugin! I use it all the time.
