### ISSUE TITLE
I nominate this for most over-engineered project of the decade.

### ISSUE THREAD

**Issue by JesseAdam** [ligos/readablepassphrasegenerator#12]
We are using this to generate non-sense passphrases, why would we need a structured dictionary with all the modifiers for tense and part of speech? This is the kind thing that's really only important for natural language processing or complex partial-match dictionary queries.

Other than the dictionary requirements, the plugin is great, thanks!

**Comment by ligos** [comment]
Nomination accepted ;-)

You can always generate a bunch of random words, like below. But there are a stack of other sites / plugins that do "correct horse battery staple" already.
https://makemeapassword.ligos.net/generate/passphrase
