### ISSUE TITLE
KeePass showing this plugin current revision incorrectly

### ISSUE THREAD

**Issue by Naugrimohtar** [ligos/readablepassphrasegenerator#13]
KeePass's 'update check' window is showing an on 'pre-release' version and status. I am not sure if that is just an issue on my end (in case asking for help on how to fix), or if there is some other configuration to correct this?

<img width="439" alt="Capture" src="https://user-images.githubusercontent.com/28710488/127517376-544d5bf6-2fb0-4286-816a-aa6cd82df62f.PNG">

**Comment by ligos** [comment]
Woops! My bad.
The webserver that publishes the current version of the plugin was reverted a few weeks ago.

Should be OK now.
