### ISSUE TITLE
period at end of phrase, unwanted

### ISSUE THREAD

**Issue by Reality4DEvolution** [ligos/readablepassphrasegenerator#15]
> hello, using readable passphrase, excellent plugin.
i select the password field, in keepass, generate a password, using the READABLE PASSPHRASE algorithm, i havesome custom settings, but it always puts a period at the end of the phrase (but if i do a list preview, thre are not periods in there), i can't figure out how to get it to not put the period
thansk

**Comment by ligos** [comment]
Can you post a screenshot of your custom settings, please. I'll see if I can reproduce on my computer.

**Comment by Reality4DEvolution** [comment]
see attached
![560](https://user-images.githubusercontent.com/67389333/146453257-0a204d18-31ec-404f-ba35-0285d6c4595a.jpg)
![554](https://user-images.githubusercontent.com/67389333/146453258-68625797-8ffc-47f8-9eb1-fc0a6aae2534.jpg)
![556](https://user-images.githubusercontent.com/67389333/146453260-ef933913-9341-4ed0-9fe0-f629d53ae05a.jpg)
![558](https://user-images.githubusercontent.com/67389333/146453261-f647bdea-ee7e-41c3-9fc9-62402a3c88e0.jpg)
[

**Comment by ligos** [comment]
Thanks for the screenshots!

Looks like your *Constant Style* is set to *EndOfPhrase* with a value of `.` (a period). Pretty sure it's exactly one pixel (at least on my screen)!

![image](https://user-images.githubusercontent.com/3079652/146534826-a30cd18e-7bd3-4b0d-87d4-e5400d485228.png)

![image](https://user-images.githubusercontent.com/3079652/146534870-73243978-550a-4e53-b4f2-cdcac6102cf7.png)


Changing to *Never* should remove your unwanted period.

![image](https://user-images.githubusercontent.com/3079652/146534524-c036a613-7c40-492d-9263-0e764583c7da.png)

![image](https://user-images.githubusercontent.com/3079652/146534588-3dbe002c-fa51-4b8b-9f98-e981485a06c0.png)

**Comment by Reality4DEvolution** [comment]
i am 67. i have trifocals.  i got an epiretinal membrane (blurs vision slightly) - I SEARCHED for a "period" high and low !!!  I thought i was going nuts !

BUT, see next set of attached.  I CHANGED the options,  but they do not seem to STAY IN EFFECT, it reverted back to  END OF PHRASE instead of NEVER, and added a period...
![566](https://user-images.githubusercontent.com/67389333/146547058-30bf686d-d8fb-43fa-8ea0-0df25a2b0f75.jpg)
![568](https://user-images.githubusercontent.com/67389333/146547059-b55c68a8-4726-4034-b345-2b6818d3901b.jpg)
![570](https://user-images.githubusercontent.com/67389333/146547060-a6f1f91a-80ba-4706-834f-de52cc91df3a.jpg)
![572](https://user-images.githubusercontent.com/67389333/146547061-fb3b4e74-60fd-4100-9a8b-d09ebd39e661.jpg)
.

**Comment by ligos** [comment]
Hmm... I ran into similar... inconsistencies when customising settings. I *think* this is KeePass itself doing something unusual.

The most reliable way of [saving custom settings is a Profile](https://keepass.info/help/base/pwgenerator.html). 

**Step 1 - Configure the Plugin According to Your Preference**

![image](https://user-images.githubusercontent.com/3079652/146627443-e465ec8c-110e-4486-a79c-1b6201ffefec.png)

Click OK.

**Step 2 - Save as a Custom Profile**

Do this *before* you click OK or jump to any other screen.

![image](https://user-images.githubusercontent.com/3079652/146627460-95358ee5-d60b-4724-b832-c8ce734de743.png)

![image](https://user-images.githubusercontent.com/3079652/146627478-4b9c690f-1948-4345-991d-788668412287.png)

![image](https://user-images.githubusercontent.com/3079652/146627487-07a3e55d-1ac1-489c-aa06-da3937f42bd9.png)

**Step 3 - When Generating a new Password, use your Custom Profile**

![image](https://user-images.githubusercontent.com/3079652/146627516-888fe950-885e-4f99-a777-c0acd30194f6.png)

![image](https://user-images.githubusercontent.com/3079652/146627526-45f05468-2e92-4fcf-a3f6-24f3dc3379f7.png)

**Step 4 - Donate lots of Money**

OK, this is very optional ;-)

**Comment by Reality4DEvolution** [comment]
it WORKED !
I did as above, fixed the options, SAVED as custom - ReadablePassPhrase-MODIFIED, then went to generate a new password with that, and it kept the "period" out", and held the END OF PHRASE as NEVER !
You have done an excellent psychiatric session today, at least proved that i'm not crazy (yet).

re: STEP 4, donate lots of money - is there a separate donation for ReadablePasswordGenerator?
I've donated several times to Keepass - out of all programs, this i believe is the most valuable program on my machine !  several family members use it also, and we're using ReadablePassphrase to generate the passcodes, because that way, in event we ever have to TYPE them, (there are sites that do NOT ALLOW pasting of passwords !!), we can easily type nonsensical word phrases, rather than random characters !

when i continually hear news stories about "protect your password, don't let others see you type it, etc" it drives me NUTS !
I ahve over 400 entries in KeePass, for logins !  I have gradualy been converting all passwords to a ReadablePassphrase.

Take care, have a great day !
nick


!

**Comment by ligos** [comment]
Glad to help :-)
And I agree, password managers (whichever one you choose) are the great unsung hero of the 21st century.

There's a donate button on the [main Github page for Readable Passphrase Generator](https://github.com/ligos/readablepassphrasegenerator). Do with it what you will!

**Comment by Reality4DEvolution** [comment]
thanks, found it !
the DONATE page locks in AUD rates, can't show U.S. rates, have to wait for conversion, so it sent some odd number instead of an even amount  :-)  
Thanks very much, keep up the good work, and have a great day !

**Comment by ligos** [comment]
Donation received with thanks :-)
Glad Readable Passphrase Generator is so helpful for you
