### ISSUE TITLE
wrong tooltip for fake words switch

### ISSUE THREAD

**Issue by TimetravelerDD** [ligos/readablepassphrasegenerator#17]
![image](https://user-images.githubusercontent.com/14355674/174063667-6272ed0d-a88f-4391-bc03-526ba65b20dc.png)

please forgive the brief post, but I think the screenshot and the title are self-explanatory

Thank you!

**Comment by ligos** [comment]
Copy and paste strikes again!

**Comment by BaileyFurrow** [comment]
This has been fixed; issue can be closed.
![image](https://github.com/ligos/readablepassphrasegenerator/assets/66973680/f85f6560-2202-45c8-8588-ebd0915713c4)
