### ISSUE TITLE
Numeric Style Mutator ignored when Uppercase Style set to "Never"

### ISSUE THREAD

**Issue by saberblaze** [ligos/readablepassphrasegenerator#2]
As the title states,  if mutators is set to custom and uppercase style is set to "never" then the generator will not add any numbers when generating the password. When uppercase style is set to anything other then "never" than the rules for the numeric style kick in. Using latest version of both, KeePass 2.44 and 1.2 of plugin, although the same issue was present in earlier versions of both as well.

**Comment by ligos** [comment]
Thanks @saberblaze. I've replicated this on my computer. I'll work on a fix at some point.

**Comment by saberblaze** [comment]
Awesome, glad to hear.

**Comment by ligos** [comment]
Fixed in [Version 1.2.1](https://github.com/ligos/readablepassphrasegenerator/releases/tag/release-1.2.1)
