### ISSUE TITLE
More than one constant mutator?

### ISSUE THREAD

**Issue by BubiBalboa** [ligos/readablepassphrasegenerator#6]
Is it possible to use more than one type of constant mutator? I would like to randomly use different punctuation marks but I couldn't figure out how to add more than one.

And can we use more than one constant mutator per passphrase?

**Comment by ligos** [comment]
Sorry, no. Only one character can be used for the constant mutator.

You can kinda have two by choosing a different word separator, but that's definitely a hack!

The purpose of the constant mutator is to meet "password complexity requirements" where your password must have an upper case, lower case, number and punctuation character. It is not there to add complexity to your passphrase; to do that, you should use a longer phrase!

**Comment by BubiBalboa** [comment]
Thanks for the explanation!

Still a little sad that I can't randomly expect my phrases to change from normal sentences to questions but I guess I can live with that.

**Comment by ligos** [comment]
The generator won't *automatically* change the trailing `.` to a `?`. But nothing stopping you rolling a dice or flipping a coin or whatever to make that change *manually*.

Aside: The phrases generated may already contain direct speech and questions, I have just never been motivated enough to implement punctuation. If that's the kind of thing you're asking for, you should open a new issue! (It certainly won't happen quickly, but if a few people are interested, it will probably happen eventually).

**Comment by ligos** [comment]
Actually, if you have some powershell or bash scripting skills, you could automate this using the console app.

**Comment by BubiBalboa** [comment]
Ha! I play around with the console but I'm definitely more comfortable with a GUI. And frankly I don't care enough to wrap my head around what would be necessary to pull this off. But nice to know it would be possible.

 So the issue should be a feature request to match the punctuation to the actual phrase? I'd need to keep the option to replace . with ! though. I like my passphrases the be enthusiastic. :)

**Comment by ligos** [comment]
The grammar of the phrase is weighted (that is, 20% change of a past tense verb, 50% change of present tense, etc). Don't see why punctuation couldn't have the same thing (60% chance of `.`, 20% change of `?`, 20% chance of `!`).

**Comment by BubiBalboa** [comment]
That sounds cool.

**Comment by ligos** [comment]
Closed.
Added feature request to #7
