### ISSUE TITLE
Allow also picking password length in terms of word count

### ISSUE THREAD

**Issue by benedictleejh** [ligos/readablepassphrasegenerator#8]
Currently, password length is decided by the number of characters only. For a passphrase, it feels more natural to consider it in terms of number of words.

Adding a word count selection would also be useful for the times we want to generate a passphrase in terms of that. Say if you want a 15 word passphrase as a master password, you could just generate phrases of that length, instead of generating a list until you see phrases of the length you want.

**Comment by ligos** [comment]
Thanks for the idea. I'll consider it for future versions.

**Comment by ligos** [comment]
This will be included in the upcoming 1.3.0 version!

**Comment by ProNotion** [comment]
How do we go about using this feature?

**Comment by ligos** [comment]
You simply need to _Generate Passphrase Between X and Y **Words** Long_

![image](https://user-images.githubusercontent.com/3079652/184129505-2d2b8ce1-0692-4857-bcb0-aebcdfc30607.png)

Or, on the console application, use the `--countBy word` option:

```
PS> PassphraseGenerator.exe --countby word --min 6 --max 8
```

**Comment by markandgo** [comment]
> You simply need to _Generate Passphrase Between X and Y **Words** Long_
> 
> ![image](https://user-images.githubusercontent.com/3079652/184129505-2d2b8ce1-0692-4857-bcb0-aebcdfc30607.png)
> 
> Or, on the console application, use the `--countBy word` option:
> 
> ```
> PS> PassphraseGenerator.exe --countby word --min 6 --max 8
> ```

Hello. I know this was closed, but I am not understanding how this works. I set my max word count to 4 for example, and I see that I generate a passphrase with more words than 4, which is not what I want. Any help? Thanks for the plugin!

**Comment by ligos** [comment]
@markandgo  Could you post a screenshot of your configuration, please? And also the content of the _Preview_ tab, so I can see what the plugin is generating.

**Comment by markandgo** [comment]
@ligos 

Sure! Here are my config and preview:

![image](https://github.com/ligos/readablepassphrasegenerator/assets/1749042/56240b0a-aefe-4a16-b012-74c26965dd92)

![image](https://github.com/ligos/readablepassphrasegenerator/assets/1749042/6ec32900-4665-4806-8ad6-cc5eef8cb869)

**Comment by ligos** [comment]
@markandgo Can you try again with _Word Separator_ = _Space_ or _Custom_, please? 

I think the code which counts the number of words runs after the phrase is generated. If there's no separator, then there's no way to tell words apart.

**Comment by markandgo** [comment]
@ligos 

It works! The output is as expected for "Custom" separator as well.

![image](https://github.com/ligos/readablepassphrasegenerator/assets/1749042/8c4cdb80-301d-4422-ac56-8ffdcb2a594d)

![image](https://github.com/ligos/readablepassphrasegenerator/assets/1749042/6c6d62cf-fc98-46a3-99a5-7877a9b065f5)
